#!/bin/bash
set -euo pipefail

source bootstrap.env

if [[ $PLATFORM == openshift ]]; then
  sudo oc login -u $OSHIFT_CLUSTER_ADMIN_USERNAME
fi


./0_check_dependencies.sh

./stop

./1_create_conjur_namespace.sh
./2_build_and_push_containers.sh
./3_deploy_conjur_followers.sh
./4_configure_followers.sh
